FROM node:18-alpine AS builder
WORKDIR /app

# Copy package.json only
COPY package.json ./
RUN npm cache clean --force && npm install

# Copy source and build distribution
COPY . .
RUN npm run build

FROM nginx:alpine
COPY nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=builder /app/dist /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]