services:
  backend:
    build:
      context: ./backend
      dockerfile: DockerFile
    container_name: demon_backend
    ports:
      - "8000:8000"
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: DockerFile
    container_name: demon_frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    restart: unless-stopped