services:
  redis:
    image: "redis:alpine"
    container_name: demon_redis
    ports:
      - "6379:6379"

  backend:
    build:
      context: ./backend
      dockerfile: DockerFile
    container_name: demon_backend
    ports:
      - "8000:8000"
    environment:
      - AWS_DEFAULT_REGION=us-east-1
      - DB_DIR=/app/db
      - SHIFT_TIMEZONE=Asia/Kolkata
      - DEMO_MODE=1
      - REDIS_URL=redis://redis:6379/0
    volumes:
      - db_data:/app/db
    depends_on:
      - redis
    restart: unless-stopped

  celery_worker:
    build:
      context: ./backend
      dockerfile: DockerFile
    container_name: demon_celery
    command: celery -A scheduler worker --loglevel=info -B
    environment:
      - REDIS_URL=redis://redis:6379/0
      - AWS_DEFAULT_REGION=us-east-1
      - DB_DIR=/app/db
      - SHIFT_TIMEZONE=Asia/Kolkata
      - DEMO_MODE=1
    volumes:
      - db_data:/app/db
    depends_on:
      - redis
      - backend
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: DockerFile
    container_name: demon_frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  db_data:
